spring:
  batch:
    job:
      enabled: false

  datasource:
    url: ${JDBC_DATABASE_URL:postgres://root:XuobO2YH6FHQF8S25hZpiGTLttUhndMN@dpg-cm02id6d3nmc738icvh0-a.frankfurt-postgres.render.com/postgres1_cb9c}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:XuobO2YH6FHQF8S25hZpiGTLttUhndMN}
    dbcp2:
      max-wait-millis: 30000
      validation-query: select 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
    show-sql: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
springdoc:
  pathsToMatch: /api/**